Functions? Everybody has functions. Functions are a part of reality.

diff --git a/shell/functions b/shell/functions
--- a/shell/functions
+++ b/shell/functions
@@ -1,8 +1,13 @@
 #!/usr/bin/env bash
 
 function httpless {
-  # `httpless example.org'
-  http --pretty=all --print=HBhb "$@" | less -R;
+  # httpless 'https://cms.thescore.com/news/1249197'
+  http --pretty=colors --print=HBhb "$@" | less -R;
+}
+
+function httpless_no_color_no_pager {
+  # httpless_no_color_no_pager --json GET 'https://cms.thescore.com/api/v2/news/1249197.json'
+  http --pretty=none --print=HBhb "$@";
 }
 
 function httpperf {
@@ -16,7 +21,7 @@ function jqbrowser {
   open -b 'com.google.chrome' "${TMPFILE}"
 }
 
-function sscreencapture-in-2-seconds-send-to-desktop {
+function sscreencapture_in_2_seconds_send_to_desktop {
   screencapture -T2 -S -x "$HOME/Desktop/screenshot-$(date +%Y-%m-%d__%H_%M_%S).png"
 }
 
@@ -61,4 +66,55 @@ function e  () {
   else
     subl -n ./
   fi
+}
+
+# proxy funcs from https://wiki.archlinux.org/index.php/proxy_settings
+# to use type `proxy_on` and follow instructions
+function proxy_on() {
+    export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com"
+
+    if (( $# > 0 )); then
+        valid=$(echo $@ | sed -n 's/\([0-9]\{1,3\}.\)\{4\}:\([0-9]\+\)/&/p')
+        if [[ $valid != $@ ]]; then
+            >&2 echo "Invalid address"
+            return 1
+        fi
+
+        export http_proxy="http://$1/"
+        export https_proxy=$http_proxy
+        export ftp_proxy=$http_proxy
+        export rsync_proxy=$http_proxy
+        echo "Proxy environment variable set."
+        return 0
+    fi
+
+    echo -n "username: "; read username
+    if [[ $username != "" ]]; then
+        echo -n "password: "
+        read -es password
+        local pre="$username:$password@"
+    fi
+
+    echo -n "server: "; read server
+    echo -n "port: "; read port
+    export http_proxy="http://$pre$server:$port/"
+    export https_proxy=$http_proxy
+    export ftp_proxy=$http_proxy
+    export rsync_proxy=$http_proxy
+    export HTTP_PROXY=$http_proxy
+    export HTTPS_PROXY=$http_proxy
+    export FTP_PROXY=$http_proxy
+    export RSYNC_PROXY=$http_proxy
+}
+
+function proxy_off(){
+    unset http_proxy
+    unset https_proxy
+    unset ftp_proxy
+    unset rsync_proxy
+    unset HTTP_PROXY
+    unset HTTPS_PROXY
+    unset FTP_PROXY
+    unset RSYNC_PROXY
+    echo -e "Proxy environment variable removed."
 }
